import type { WelcomeMockPost } from './welcomePhoneTypes';

/** Sample feed for the welcome page phone — illustrative only, not live data. */
export const WELCOME_MOCK_POSTS: WelcomeMockPost[] = [
  {
    id: 'mock-maya',
    displayName: 'Maya',
    username: 'mayamakes',
    timeLabel: '3m',
    initial: 'M',
    avatarTone: '',
    content: 'What’s one tiny thing you changed that made your days noticeably better?',
    likesCount: 42,
    commentsCount: 18,
  },
  {
    id: 'mock-rin-poll',
    displayName: 'Rin',
    username: 'rinreads',
    timeLabel: '12m',
    initial: 'R',
    avatarTone: 'orange',
    content: 'Pick tomorrow’s reading spot:',
    likesCount: 8,
    commentsCount: 11,
    poll: [
      { label: 'Park bench', fillPercent: 68 },
      { label: 'Corner café', fillPercent: 32 },
    ],
  },
  {
    id: 'mock-arun',
    displayName: 'Arun',
    username: 'arunoutside',
    timeLabel: '21m',
    initial: 'A',
    avatarTone: 'green',
    content: 'Blue hour after the rain. Worth the wait.',
    likesCount: 27,
    commentsCount: 6,
    mediaHint: 'Photo',
  },
  {
    id: 'mock-noor',
    displayName: 'Noor',
    username: 'noorthinks',
    timeLabel: '34m',
    initial: 'N',
    avatarTone: '',
    content:
      'What’s something you believed five years ago that you see completely differently now?',
    likesCount: 64,
    commentsCount: 31,
  },
  {
    id: 'mock-jules',
    displayName: 'Jules',
    username: 'juleswrites',
    timeLabel: '48m',
    initial: 'J',
    avatarTone: 'orange',
    content:
      'Today was messy. I still showed up for the part that mattered, and I’m letting that be enough.',
    likesCount: 83,
    commentsCount: 19,
  },
  {
    id: 'mock-liv-poll',
    displayName: 'Liv',
    username: 'livlaughs',
    timeLabel: '1h',
    initial: 'L',
    avatarTone: 'orange',
    content: 'You get one oddly specific superpower. I’m choosing:',
    likesCount: 117,
    commentsCount: 46,
    poll: [
      { label: 'Cool side of any pillow', fillPercent: 52 },
      { label: 'Always find matching socks', fillPercent: 31 },
      { label: 'Perfect toast every time', fillPercent: 17 },
    ],
  },
  {
    id: 'mock-theo',
    displayName: 'Theo',
    username: 'theobuilds',
    timeLabel: '1h',
    initial: 'T',
    avatarTone: 'green',
    content:
      'Try making tomorrow’s first decision tonight. Mine is simple: shoes by the door, walk before screens.',
    likesCount: 48,
    commentsCount: 12,
  },
  {
    id: 'mock-sam',
    displayName: 'Sam',
    username: 'samsketches',
    timeLabel: '2h',
    initial: 'S',
    avatarTone: '',
    content: 'Morning light on the kitchen table — sketching before email exists.',
    likesCount: 15,
    commentsCount: 4,
    mediaHint: 'Photo',
  },
  {
    id: 'mock-emi-link',
    displayName: 'Emi',
    username: 'emireads',
    timeLabel: '3h',
    initial: 'E',
    avatarTone: 'green',
    content: 'This essay on attention and friendship is sticking with me.',
    likesCount: 22,
    commentsCount: 9,
    linkHint: 'Long read',
  },
  {
    id: 'mock-kai',
    displayName: 'Kai',
    username: 'kaitakes',
    timeLabel: '4h',
    initial: 'K',
    avatarTone: 'orange',
    content: 'Quiet win: replied to one thread with something useful instead of scrolling past.',
    likesCount: 36,
    commentsCount: 7,
  },
];
