/** Centralized English copy for the chat / messages panel UI. */
export const chatStrings = {
  messages: 'Messages',
  sendMessage: 'Send message',
  dismissMessages: 'Dismiss messages',
  expandMessages: 'Expand messages',
  collapseMessages: 'Collapse messages',
  backToConversations: 'Back to conversations',
  photo: 'Photo',
  unknownDate: 'Unknown date',
  removeImage: 'Remove image',
  attachImage: 'Attach image',
  choosePhoto: 'Choose photo',
  takePhoto: 'Take photo',
  capture: 'Capture',
  cancel: 'Cancel',
  newMessagesPill: 'New messages ↓',
  noMessagesYetHello: 'No messages yet. Say hello!',
  noMessagesYet: 'No messages yet',
  typing: 'Typing…',
  youPrefix: 'You: ',
  messagePlaceholder: 'Message',
  attachmentPreview: 'Attachment preview',
  cameraDialog: 'Camera',
  online: 'Online',
  offline: 'Offline',
  unreadMessages: (n: number) => `${n} unread messages`,
  newIncomingMessages: (n: number) => (n === 1 ? '1 new message' : `${n} new messages`),
  peerTyping: (username: string) => `${username} is typing`,
} as const;
