name = "hin"
main = "src/index.ts"
compatibility_date = "2024-05-24"

[[d1_databases]]
binding = "DB"
database_name = "hin-d1"
database_id = "cca6c374-98ad-4fb7-9dca-c2b2c5c43d75"
migrations_dir = "../../packages/db/migrations"

[durable_objects]
bindings = [
  { name = "REALTIME_DO", class_name = "RealtimeDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RealtimeDO"]

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "gmart"

[vars]
GOOGLE_CLIENT_ID = "374278266123-6i29t1ve6t76cdb6vsvumvn4nghonpd8.apps.googleusercontent.com"
